remotes::install_version("mgcv", "1.8-24")
remotes::install_version("ggplot2", "3.0.0")
remotes::install_version("gamair", "1.0-0", type="source")
remotes::install_version("sp", "1.3-1")
remotes::install_version("MASS", "7.3-50")
remotes::install_github("datacamp/testwhat@v4.9.8")
