library(webdriver)
library(jsonlite)

pjs <- run_phantomjs()
ses <- Session$new(port = pjs$port)
ses$go(paste0("https://vizhub.healthdata.org/gbd-foresight/"))
email_field <- ses$findElement(xpath = '//*[@id="sign-in-form-fields-root"]/div/label[1]/input')
pwd_field <- ses$findElement(xpath = '//*[@id="sign-in-form-fields-root"]/div/label[2]/input')
login_btn <- ses$findElement(xpath = '//*[@id="sign-in-form-fields-root"]/div/label[3]/input')
email_field$sendKeys(email)
pwd_field$sendKeys(pwd)
login_btn$click()
schema_json <- ses$executeScript(schema_js_code)
schema <- jsonlite::fromJSON(schema_json, simplifyVector = FALSE)
return(schema)
